---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: "{{ logstash_key }}"
    state: present

- name: Add Logstash repository.
  template:
    src: logstash.repo.j2
    dest: /etc/yum.repos.d/logstash.repo
    owner: root
    group: root
    mode: 0644

- name: Install Logstash.
  yum: pkg=logstash state=present
