---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: "{{ logstash_key }}"
    state: present

- name: Add Logstash repository.
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    mode: 0644

- name: Create Logstash configuration file for local syslog.
  template:
    src: 02-local-syslog-input.conf.j2
    dest: /etc/logstash/conf.d/02-local-syslog-input.conf
    owner: root
    group: root
    mode: 0644

- name: Install Logstash.
  yum: pkg=logstash state=present
