---
- name: Converge
  hosts: all
  become: true

  vars:
    logstash_enabled_on_boot: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.java
    - manticore.elasticsearch
    - manticore.logstash
