---
- src: geerlingguy.java
- src: https://github.com/mgiustiniani/ansible-role-elasticsearch.git
  name: manticore.elasticsearch
- src: https://github.com/mgiustiniani/ansible-role-logstash.git
  name: manticore.logstash
